// Downloads the named glyphs declared in emoji-manifest.json from the Iconify API
// and bundles their SVG markup into src/assets/emojiData.ts so the app renders a
// consistent icon collection (Fluent Emoji Flat + circle-flags) on every platform,
// independent of the OS emoji font. Re-run after editing the manifest.
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

const manifest = JSON.parse(
  await readFile(join(__dirname, 'emoji-manifest.json'), 'utf8'),
);

const entries = Object.entries(manifest).filter(([k]) => !k.startsWith('_'));

const out = {};
const missing = [];

async function fetchIcon(id) {
  const url = `https://api.iconify.design/${id}.svg`;
  const res = await fetch(url);
  if (!res.ok) return null;
  const text = await res.text();
  if (!text.trim().startsWith('<svg')) return null;
  return text;
}

for (const [key, id] of entries) {
  process.stdout.write(`• ${key} (${id}) … `);
  try {
    const svg = await fetchIcon(id);
    if (!svg) {
      missing.push(`${key} -> ${id}`);
      console.log('MISSING');
      continue;
    }
    // strip width/height so the component controls sizing via viewBox
    const cleaned = svg
      .replace(/\s(width|height)="[^"]*"/g, '')
      .replace(/\n/g, ' ')
      .trim();
    out[key] = cleaned;
    console.log('ok');
  } catch (e) {
    missing.push(`${key} -> ${id} (${e.message})`);
    console.log('ERROR');
  }
}

const header = `// AUTO-GENERATED by scripts/build-emoji.mjs — do not edit by hand.
// Source collections: Fluent Emoji Flat (MIT, Microsoft) and circle-flags (MIT).
/* eslint-disable */
export const EMOJI_SVG: Record<string, string> = `;

const body = JSON.stringify(out, null, 2);

await writeFile(
  join(root, 'src/assets/emojiData.ts'),
  `${header}${body};\n\nexport type EmojiName = keyof typeof EMOJI_SVG;\n`,
  'utf8',
);

console.log(`\nWrote ${Object.keys(out).length} glyphs to src/assets/emojiData.ts`);
if (missing.length) {
  console.log(`\n${missing.length} MISSING (fix manifest):`);
  for (const m of missing) console.log('  - ' + m);
  process.exitCode = 2;
}
